In [1]:
import numpy as np
matrix = np.matrix("1,5,7;2,6,9;4,8,3")
multiple = matrix * 2
print(multiple)
multiple[multiple > 10] = 0
print(multiple)

[[ 2 10 14]
 [ 4 12 18]
 [ 8 16  6]]
[[ 2 10  0]
 [ 4  0  0]
 [ 8  0  6]]


In [3]:
arr = np.random.randint(1, 101, 20)
print(arr)
div_5 = arr[arr % 5 == 0]
print("элементы, которые делятся на 5 без остатка:\n", div_5)
arr[arr % 5 == 0] = -1
print("Обновлённый массив:\n", arr)

[54 37 31 32  8 24 11 30 38 99 10 33 22  3 64 49 26 80 22  9]
элементы, которые делятся на 5 без остатка:
 [30 10 80]
Обновлённый массив:
 [54 37 31 32  8 24 11 -1 38 99 -1 33 22  3 64 49 26 -1 22  9]


In [5]:
a = np.random.randint(0, 51, 5)
print("Первый массив:\n", a)
b = np.random.randint(0, 51, 5)
print("Второй массив:\n", b)
ab = np.vstack((a,b))
print("Объединенный массив:\n", ab)
a1, b1 = np.vsplit(ab, 2)
print("Разделенные массивы:\nПервый:", a1, "\nВторой:", b1)

Первый массив:
 [50 50 44 26 36]
Второй массив:
 [25  8 16 39  7]
Объединенный массив:
 [[50 50 44 26 36]
 [25  8 16 39  7]]
Разделенные массивы:
Первый: [[50 50 44 26 36]] 
Второй: [[25  8 16 39  7]]


In [7]:
a = np.linspace(-10, 10, 50, dtype = int)
print("Созданный массив: ", a)
summ_all = np.sum(a)
print("Сумма всех элементов: ", summ_all)
pos_summ = np.sum(a[a > 0])
print("Сумма положительных элементов: ", pos_summ)
neg_summ = np.sum(a[a < 0])
print("Сумма отрицательных элементов: ", neg_summ)

Созданный массив:  [-10 -10 -10  -9  -9  -8  -8  -8  -7  -7  -6  -6  -6  -5  -5  -4  -4  -4
  -3  -3  -2  -2  -2  -1  -1   0   0   1   1   1   2   2   3   3   3   4
   4   5   5   5   6   6   7   7   7   8   8   9   9  10]
Сумма всех элементов:  -24
Сумма положительных элементов:  116
Сумма отрицательных элементов:  -140


In [9]:
edm = np.identity(4)
print("Единичная матрица: \n", edm)
diagm = np.diag([5, 10, 15, 20])
print("Диагональная матрица:\n", diagm)
edm_summ = np.sum(edm)
print("Сумма элементов единичной матрицы:\n", edm_summ)
diagm_summ = np.sum(diagm)
print("Сумма элементов диагональной матрицы:\n", diagm_summ)
print("По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.")

Единичная матрица: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы:
 4.0
Сумма элементов диагональной матрицы:
 50
По результатам сумма элементов диагональной матрицы оказалась больше, чем единичной.


In [11]:
a = np.random.randint(1, 21, (3, 3))
print("Первая матрица:\n", a)
b = np.random.randint(1, 21, (3, 3))
print("Вторая матрица:\n", b)
summ = a + b
print("Сумма: ", summ)
razn = a - b
print("Разница: ", razn)
proz = a * b
print("Произведение: ", proz)

Первая матрица:
 [[12 16 20]
 [11 16  2]
 [12 13  6]]
Вторая матрица:
 [[11 15  6]
 [15 10 16]
 [11 11  8]]
Сумма:  [[23 31 26]
 [26 26 18]
 [23 24 14]]
Разница:  [[  1   1  14]
 [ -4   6 -14]
 [  1   2  -2]]
Произведение:  [[132 240 120]
 [165 160  32]
 [132 143  48]]


In [13]:
a = np.random.randint(1, 11, (2, 3))
print("Первая матрица:\n", a)
b = np.random.randint(1, 11, (3, 2))
print("Вторая матрица:\n", b)
mult = a @ b
print("Матричное умножение:\n", mult)

Первая матрица:
 [[ 8  4  2]
 [10  5  3]]
Вторая матрица:
 [[5 4]
 [3 7]
 [2 2]]
Матричное умножение:
 [[56 64]
 [71 81]]


In [15]:
a = np.random.randint(1, 21, (3, 3))
print("Матрица:\n", a)
det = np.linalg.det(a)
print("Определитель:\n", det)
if np.isclose(det, 0):
    inv = "Матрица вырождена"
else:
    inv = np.linalg.inv(a)
print("Обратная матрица:\n", inv)

Матрица:
 [[16 17 16]
 [13  9  1]
 [20 12  9]]
Определитель:
 -928.9999999999997
Обратная матрица:
 [[-0.07427341 -0.04198062  0.13670614]
 [ 0.10441335  0.18945102 -0.20667384]
 [ 0.02583423 -0.15931109  0.08288482]]


In [17]:
a = np.random.randint(1, 51, (4, 4))
print("Матрица:\n", a)
transp = a.T
print("Транспонированная матрица:\n", transp)
value = np.trace(a)
print("След матрицы:\n", value)

Матрица:
 [[15 15 12 46]
 [ 9 27 22  4]
 [ 1 44 16 16]
 [29 19 13 47]]
Транспонированная матрица:
 [[15  9  1 29]
 [15 27 44 19]
 [12 22 16 13]
 [46  4 16 47]]
След матрицы:
 105


In [19]:
A = np.array([[2, 3, -1],
             [4, -1, 2],
             [-3, 5, 4]])
B = np.array([5, 6, -2])
res = np.linalg.solve(A, B)
print("Решение системы: ", res)

Решение системы:  [1.63963964 0.57657658 0.00900901]
